### ISSUE TITLE
which Arduino boards are supported ?

### ISSUE THREAD

**Issue by fatmehosseini** [Seeed-Studio/Seeed_Arduino_FS#11]
Hi, 
https://www.arduino.cc/reference/en/libraries/seeed-arduino-sfud/
In this link mentioned that your library support all architectures, but when I am trying to upload it's examples on Arduino nano it doesn't work. and error compiling for board Arduino nano. while it compiles for esp8266 board.

**Comment by LynnL4** [comment]
hi, Tested on samd series, esp should have a better way to manipulate files

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
