### ISSUE TITLE
Date & Time of file creation is always 12/31/2017 11pm and incorrect

### ISSUE THREAD

**Issue by RaphTronic** [Seeed-Studio/Seeed_Arduino_FS#15]
How can files created by Seeed_Arduino_FS show the correct date / time ?

Using the ReadWrite example from the Seeed_Arduino_FS library, all the files generated show a Date Created/Modified value of 12/31/2017 11pm under Windows. Regardless of the WIO RTC's actual date/time at the time of the file creation.

I could not find any WIO Terminal code example that properly initializes the file system's date. On non-WIO Arduino platforms the call  SdFile::dateTimeCallback(dateTime); is used for that purpose but it does not seem to be supported by Seeed_Arduino_FS.

**Comment by LynnL4** [comment]
I'm sorry, time recording is disabled by default

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
