### ISSUE TITLE
Closing a file prints a '0'

### ISSUE THREAD

**Issue by dennisma** [Seeed-Studio/Seeed_Arduino_FS#5]
In the File::close() method there is a Serial.println that prints the return value from f_close().   This is on line 191 in file Seeed_FS.cpp.

This causes issues if people are opening files and displaying the value in the Serial plotter as it prints a 0 as part of the data set.

**Comment by Hansen0314** [comment]
can you give me more information about this issue? I cannot find any errors for now.there does not exist  Serial.println in File:: close().

**Comment by dennisma** [comment]
My apologies.  I had downloaded it from the beta branch.  The file I was referring to is here: https://github.com/Seeed-Studio/Seeed_Arduino_FS/blob/beta/src/Seeed_FS.cpp

The WIO Terminal wiki here: https://wiki.seeedstudio.com/Wio-Terminal-FS-Overview/  links to the beta branch of the SD library.

Sorry.
