### ISSUE TITLE
Incorrect comparison leaves unprotected call to f_read( ) within read( ) method

### ISSUE THREAD

**Issue by dspdon** [Seeed-Studio/Seeed_Arduino_FS#6]
**Describe the bug**
An incorrect constant being used in a comparison invalidates the test of whether f_read( ) succeeds.  This can cause issues when calling the public "read(buf, nbyte)" method within Seeed_FS.cpp

The current code will always pass the test, since f_read() returns an unsigned enum and the test is against the constant "-1".  The call to f_read() is thereby left untested.  The code is in Seeed_FS.cpp on line 130, the relevant code fragment is this:

if (f_read(_file, buf, nbyte, &t) == -1) {  // <-- that's the problem constant
  return 0;
} else {
  return t;
}

The invalid type comparison was flagged by the compiler while using "-Wall" and recompiling all source in a recent project.  The "-1" constant can be replaced by the enumeration value "FR_OK", and the polarity of the test reversed.  A minimal code change would go something like this:

if (f_read(_file, buf, nbyte, &t) == FR_OK) {
  return t;
} else {
  return 0;
}

**To Reproduce**
I don't offer steps to reproduce the failure behavior.

However, here is the compiler output when using "-Wall" and recompiling source code from scratch:

"C:\\Users\\don_o\\AppData\\Local\\Arduino15\\packages\\Seeeduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -Wall -Wextra -Wno-expansion-to-defined -std=gnu++14 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions <... many more parameters here ...>

C:\Users\don_o\OneDrive\Documents\Arduino\libraries\Seeed_Arduino_FS-master\src\Seeed_FS.cpp: In member function 'long int fs::File::read(void*, uint32_t)':
C:\Users\don_o\OneDrive\Documents\Arduino\libraries\Seeed_Arduino_FS-master\src\Seeed_FS.cpp:130:43: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         if (f_read(_file, buf, nbyte, &t) == -1) {

**Expected behavior**
Without this change, the read( ) method will return an erroneous value to the caller whenever f_read( ) fails.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by Pillar1989** [comment]
Thanks for your analysis, can you submit a PR to us for fixing the bug? We are looking forward to having your trace in the code.
 @dspdon

**Comment by dspdon** [comment]
PR created - let me know if you have any questions, tested locally with an example using Arduino 1.8.13 and Seeed Wio Terminal

**Comment by Pillar1989** [comment]
Thank you
