### ISSUE TITLE
Scope problem of SD instance (not work out of main ino program)

### ISSUE THREAD

**Issue by xreef** [Seeed-Studio/Seeed_Arduino_FS#8]
Hi,
I integrate Wio Terminal in my library SimpleFTPServer (in this branch for now https://github.com/xreef/SimpleFTPServer/tree/wio_terminal_test) and It's work like an FTP server that share SD content, but I can't use Seeed_SD because It doesn't work in a scope different from main program, I can get list of file from main.ino program, but not from inside the library.
Here the configuration and the examples ino file:
(configuration with Seeed_SD)
https://github.com/xreef/SimpleFTPServer/blob/005d8c1e1a0812af791cb43569d97d6be53e2ef8/FtpServerKey.h 
(Example with Seeed_SD)
https://github.com/xreef/SimpleFTPServer/blob/631efc2d15a568f804c7656b71167e3bb2deacc3/examples/FTPServer_wio_terminal/FTPServer_wio_terminal.ino

In the current branch you can find the working version that use SdFat library.

Here the history of the bug and implementation.
https://forum.seeedstudio.com/t/low-level-debug-or-free-memory-on-wio-terminal/258726/10

You must configure the ftp client like the one in this my article.
https://www.mischianti.org/2020/02/08/ftp-server-on-esp8266-and-esp32/

Bye Renzo

**Comment by Pillar1989** [comment]
@xreef  will you try the new updates ?

**Comment by xreef** [comment]
@Pillar1989 I check It and now It's working. 
I see that you had change the manage of Flash via Filesystem with a basic SPI implementation, you think that reintroduce the filesystem management also in the future?
Bye Renzo
