### ISSUE TITLE
Version 2.1.0 is not available in the Arduino IDE

### ISSUE THREAD

**Issue by jimbobbennett** [Seeed-Studio/Seeed_Arduino_FS#9]
The `library.properties` file refers to version 2.1.0, and this contains a fix to a problem where writing in different `loop` runs would not write anything to a file. This is available in [PlatformIO](https://platformio.org/lib/show/11666/Seeed%20Arduino%20FS/installation), but not in the Arduino IDE.

Can you publish it there please, I think you just need to tag the repo at the appropriate commit with the version.

**Comment by Pillar1989** [comment]
@lakshanthad  pls

**Comment by lakshanthad** [comment]
Its done. @jimbobbennett . now the version is v2.1.1

**Comment by jimbobbennett** [comment]
Thanks - I can now see this in the Arduino IDE
